### ISSUE TITLE
Gauge Panels return N/A if left running

### ISSUE THREAD

**Issue by daclarkson** [geerlingguy/internet-monitoring#3]
![image](https://user-images.githubusercontent.com/53654455/114909130-b6e61a80-9e14-11eb-8244-b749ce3b3b57.png)

Left docker containers running for over 24 hours and all three gauges started to return N/A.

Fixed by removing the "max data points" in the query options for the panels.

I am by no means an expert in this, I just like to play around with cool projects.  Is this the correct way to resolve?

**Comment by daclarkson** [comment]
Ah, I see my issue is down leaving the time picker at 24 hours too.

Every day's a school day.  :)

**Comment by ArtMason** [comment]
Mine just did this also about 12 hours ago. Everything was fine before this.

**Comment by daclarkson** [comment]
Changing the time range on the dashboard to "Last 12 hours" fixes it for me.

Looks like the default behaviour can be changed by editing the config file to 12h instead of 24h in the [ping-speed-stats.json](https://github.com/geerlingguy/internet-monitoring/blob/33dfa4f8a8762f3ead426280f3cfa50995cf230b/grafana/provisioning/dashboards/ping-speed-stats.json#L534) file.

```
  "time": {
    "from": "now-24h",
    "to": "now"
  },
```

**Comment by maikxmh** [comment]
Hi i got the same issue. For me it seems like the query options had a problem.. changing the value of „Max data points“ to 300 (24*60/5=288 data points for 24h) fix the problem.. you are not able to save this because the dashboard is locked.. maybe the dashboard can be fixed in the repo?

thanks 

![FD5D3CC6-7026-44D7-BDFF-753D0EBF2781](https://user-images.githubusercontent.com/13382986/115030802-c83c2f00-9ec7-11eb-9023-22713aee6630.jpeg)

**Comment by geerlingguy** [comment]
Yeah I need to fix this in the repo...

**Comment by geerlingguy** [comment]
Done!
